packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  # Core dependencies (shared across multiple packages)
  zod: ^4.1.12
  hono: ^4.11.4
  better-auth: ^1.4.5
  neverthrow: "^8.1.2"

  # React ecosystem (shared across apps)
  react-hook-form: ^7.66.1
  "@hookform/resolvers": "^5.2.2"

  # TanStack Router (shared across coach-web and athlete-pwa)
  "@tanstack/react-router": ^1.136.17
  "@tanstack/router-devtools": ^1.136.17
  "@tanstack/router-plugin": ^1.136.11
  "@tanstack/react-query": ^5.90.10

  # Styling (shared across all apps)
  tailwindcss: ^4.1.17
  "@tailwindcss/vite": ^4.1.17

  # Build tools (shared across vite-based apps and server)
  vite: ^7.1.2
  wrangler: ^4.50.0
  "@vitejs/plugin-react": ^5.0.0
  "@cloudflare/vite-plugin": ^1.15.0
