/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOrgSlugRouteImport } from './routes/_authenticated/$orgSlug'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedOrgSlugExercisesRouteImport } from './routes/_authenticated/$orgSlug/exercises'
import { Route as AuthenticatedOrgSlugDashboardRouteImport } from './routes/_authenticated/$orgSlug/dashboard'
import { Route as AuthenticatedOrgSlugAthletesRouteImport } from './routes/_authenticated/$orgSlug/athletes'
import { Route as AuthenticatedOrgSlugProgramsIndexRouteImport } from './routes/_authenticated/$orgSlug/programs/index'
import { Route as AuthenticatedOrgSlugAthletesIndexRouteImport } from './routes/_authenticated/$orgSlug/athletes/index'
import { Route as AuthenticatedOrgSlugProgramsNewRouteImport } from './routes/_authenticated/$orgSlug/programs/new'
import { Route as AuthenticatedOrgSlugProgramsProgramIdRouteImport } from './routes/_authenticated/$orgSlug/programs/$programId'
import { Route as AuthenticatedOrgSlugAthletesAthleteIdIndexRouteImport } from './routes/_authenticated/$orgSlug/athletes/$athleteId/index'
import { Route as AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRouteImport } from './routes/_authenticated/$orgSlug/athletes/$athleteId/logs/index'
import { Route as AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRouteImport } from './routes/_authenticated/$orgSlug/athletes/$athleteId/log/$sessionId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgSlugRoute = AuthenticatedOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedOrgSlugExercisesRoute =
  AuthenticatedOrgSlugExercisesRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugDashboardRoute =
  AuthenticatedOrgSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugAthletesRoute =
  AuthenticatedOrgSlugAthletesRouteImport.update({
    id: '/athletes',
    path: '/athletes',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugProgramsIndexRoute =
  AuthenticatedOrgSlugProgramsIndexRouteImport.update({
    id: '/programs/',
    path: '/programs/',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugAthletesIndexRoute =
  AuthenticatedOrgSlugAthletesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgSlugAthletesRoute,
  } as any)
const AuthenticatedOrgSlugProgramsNewRoute =
  AuthenticatedOrgSlugProgramsNewRouteImport.update({
    id: '/programs/new',
    path: '/programs/new',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugProgramsProgramIdRoute =
  AuthenticatedOrgSlugProgramsProgramIdRouteImport.update({
    id: '/programs/$programId',
    path: '/programs/$programId',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugAthletesAthleteIdIndexRoute =
  AuthenticatedOrgSlugAthletesAthleteIdIndexRouteImport.update({
    id: '/$athleteId/',
    path: '/$athleteId/',
    getParentRoute: () => AuthenticatedOrgSlugAthletesRoute,
  } as any)
const AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute =
  AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRouteImport.update({
    id: '/$athleteId/logs/',
    path: '/$athleteId/logs/',
    getParentRoute: () => AuthenticatedOrgSlugAthletesRoute,
  } as any)
const AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute =
  AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRouteImport.update({
    id: '/$athleteId/log/$sessionId',
    path: '/$athleteId/log/$sessionId',
    getParentRoute: () => AuthenticatedOrgSlugAthletesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/$orgSlug': typeof AuthenticatedOrgSlugRouteWithChildren
  '/$orgSlug/athletes': typeof AuthenticatedOrgSlugAthletesRouteWithChildren
  '/$orgSlug/dashboard': typeof AuthenticatedOrgSlugDashboardRoute
  '/$orgSlug/exercises': typeof AuthenticatedOrgSlugExercisesRoute
  '/$orgSlug/programs/$programId': typeof AuthenticatedOrgSlugProgramsProgramIdRoute
  '/$orgSlug/programs/new': typeof AuthenticatedOrgSlugProgramsNewRoute
  '/$orgSlug/athletes/': typeof AuthenticatedOrgSlugAthletesIndexRoute
  '/$orgSlug/programs/': typeof AuthenticatedOrgSlugProgramsIndexRoute
  '/$orgSlug/athletes/$athleteId/': typeof AuthenticatedOrgSlugAthletesAthleteIdIndexRoute
  '/$orgSlug/athletes/$athleteId/log/$sessionId': typeof AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute
  '/$orgSlug/athletes/$athleteId/logs/': typeof AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/$orgSlug': typeof AuthenticatedOrgSlugRouteWithChildren
  '/$orgSlug/dashboard': typeof AuthenticatedOrgSlugDashboardRoute
  '/$orgSlug/exercises': typeof AuthenticatedOrgSlugExercisesRoute
  '/$orgSlug/programs/$programId': typeof AuthenticatedOrgSlugProgramsProgramIdRoute
  '/$orgSlug/programs/new': typeof AuthenticatedOrgSlugProgramsNewRoute
  '/$orgSlug/athletes': typeof AuthenticatedOrgSlugAthletesIndexRoute
  '/$orgSlug/programs': typeof AuthenticatedOrgSlugProgramsIndexRoute
  '/$orgSlug/athletes/$athleteId': typeof AuthenticatedOrgSlugAthletesAthleteIdIndexRoute
  '/$orgSlug/athletes/$athleteId/log/$sessionId': typeof AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute
  '/$orgSlug/athletes/$athleteId/logs': typeof AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authenticated/$orgSlug': typeof AuthenticatedOrgSlugRouteWithChildren
  '/_authenticated/$orgSlug/athletes': typeof AuthenticatedOrgSlugAthletesRouteWithChildren
  '/_authenticated/$orgSlug/dashboard': typeof AuthenticatedOrgSlugDashboardRoute
  '/_authenticated/$orgSlug/exercises': typeof AuthenticatedOrgSlugExercisesRoute
  '/_authenticated/$orgSlug/programs/$programId': typeof AuthenticatedOrgSlugProgramsProgramIdRoute
  '/_authenticated/$orgSlug/programs/new': typeof AuthenticatedOrgSlugProgramsNewRoute
  '/_authenticated/$orgSlug/athletes/': typeof AuthenticatedOrgSlugAthletesIndexRoute
  '/_authenticated/$orgSlug/programs/': typeof AuthenticatedOrgSlugProgramsIndexRoute
  '/_authenticated/$orgSlug/athletes/$athleteId/': typeof AuthenticatedOrgSlugAthletesAthleteIdIndexRoute
  '/_authenticated/$orgSlug/athletes/$athleteId/log/$sessionId': typeof AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute
  '/_authenticated/$orgSlug/athletes/$athleteId/logs/': typeof AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/login'
    | '/signup'
    | '/$orgSlug'
    | '/$orgSlug/athletes'
    | '/$orgSlug/dashboard'
    | '/$orgSlug/exercises'
    | '/$orgSlug/programs/$programId'
    | '/$orgSlug/programs/new'
    | '/$orgSlug/athletes/'
    | '/$orgSlug/programs/'
    | '/$orgSlug/athletes/$athleteId/'
    | '/$orgSlug/athletes/$athleteId/log/$sessionId'
    | '/$orgSlug/athletes/$athleteId/logs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/login'
    | '/signup'
    | '/$orgSlug'
    | '/$orgSlug/dashboard'
    | '/$orgSlug/exercises'
    | '/$orgSlug/programs/$programId'
    | '/$orgSlug/programs/new'
    | '/$orgSlug/athletes'
    | '/$orgSlug/programs'
    | '/$orgSlug/athletes/$athleteId'
    | '/$orgSlug/athletes/$athleteId/log/$sessionId'
    | '/$orgSlug/athletes/$athleteId/logs'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/onboarding'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_authenticated/$orgSlug'
    | '/_authenticated/$orgSlug/athletes'
    | '/_authenticated/$orgSlug/dashboard'
    | '/_authenticated/$orgSlug/exercises'
    | '/_authenticated/$orgSlug/programs/$programId'
    | '/_authenticated/$orgSlug/programs/new'
    | '/_authenticated/$orgSlug/athletes/'
    | '/_authenticated/$orgSlug/programs/'
    | '/_authenticated/$orgSlug/athletes/$athleteId/'
    | '/_authenticated/$orgSlug/athletes/$athleteId/log/$sessionId'
    | '/_authenticated/$orgSlug/athletes/$athleteId/logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$orgSlug': {
      id: '/_authenticated/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof AuthenticatedOrgSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/$orgSlug/exercises': {
      id: '/_authenticated/$orgSlug/exercises'
      path: '/exercises'
      fullPath: '/$orgSlug/exercises'
      preLoaderRoute: typeof AuthenticatedOrgSlugExercisesRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/dashboard': {
      id: '/_authenticated/$orgSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$orgSlug/dashboard'
      preLoaderRoute: typeof AuthenticatedOrgSlugDashboardRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/athletes': {
      id: '/_authenticated/$orgSlug/athletes'
      path: '/athletes'
      fullPath: '/$orgSlug/athletes'
      preLoaderRoute: typeof AuthenticatedOrgSlugAthletesRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/programs/': {
      id: '/_authenticated/$orgSlug/programs/'
      path: '/programs'
      fullPath: '/$orgSlug/programs/'
      preLoaderRoute: typeof AuthenticatedOrgSlugProgramsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/athletes/': {
      id: '/_authenticated/$orgSlug/athletes/'
      path: '/'
      fullPath: '/$orgSlug/athletes/'
      preLoaderRoute: typeof AuthenticatedOrgSlugAthletesIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugAthletesRoute
    }
    '/_authenticated/$orgSlug/programs/new': {
      id: '/_authenticated/$orgSlug/programs/new'
      path: '/programs/new'
      fullPath: '/$orgSlug/programs/new'
      preLoaderRoute: typeof AuthenticatedOrgSlugProgramsNewRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/programs/$programId': {
      id: '/_authenticated/$orgSlug/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/$orgSlug/programs/$programId'
      preLoaderRoute: typeof AuthenticatedOrgSlugProgramsProgramIdRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/athletes/$athleteId/': {
      id: '/_authenticated/$orgSlug/athletes/$athleteId/'
      path: '/$athleteId'
      fullPath: '/$orgSlug/athletes/$athleteId/'
      preLoaderRoute: typeof AuthenticatedOrgSlugAthletesAthleteIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugAthletesRoute
    }
    '/_authenticated/$orgSlug/athletes/$athleteId/logs/': {
      id: '/_authenticated/$orgSlug/athletes/$athleteId/logs/'
      path: '/$athleteId/logs'
      fullPath: '/$orgSlug/athletes/$athleteId/logs/'
      preLoaderRoute: typeof AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugAthletesRoute
    }
    '/_authenticated/$orgSlug/athletes/$athleteId/log/$sessionId': {
      id: '/_authenticated/$orgSlug/athletes/$athleteId/log/$sessionId'
      path: '/$athleteId/log/$sessionId'
      fullPath: '/$orgSlug/athletes/$athleteId/log/$sessionId'
      preLoaderRoute: typeof AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRouteImport
      parentRoute: typeof AuthenticatedOrgSlugAthletesRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedOrgSlugAthletesRouteChildren {
  AuthenticatedOrgSlugAthletesIndexRoute: typeof AuthenticatedOrgSlugAthletesIndexRoute
  AuthenticatedOrgSlugAthletesAthleteIdIndexRoute: typeof AuthenticatedOrgSlugAthletesAthleteIdIndexRoute
  AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute: typeof AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute
  AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute: typeof AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute
}

const AuthenticatedOrgSlugAthletesRouteChildren: AuthenticatedOrgSlugAthletesRouteChildren =
  {
    AuthenticatedOrgSlugAthletesIndexRoute:
      AuthenticatedOrgSlugAthletesIndexRoute,
    AuthenticatedOrgSlugAthletesAthleteIdIndexRoute:
      AuthenticatedOrgSlugAthletesAthleteIdIndexRoute,
    AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute:
      AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute,
    AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute:
      AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute,
  }

const AuthenticatedOrgSlugAthletesRouteWithChildren =
  AuthenticatedOrgSlugAthletesRoute._addFileChildren(
    AuthenticatedOrgSlugAthletesRouteChildren,
  )

interface AuthenticatedOrgSlugRouteChildren {
  AuthenticatedOrgSlugAthletesRoute: typeof AuthenticatedOrgSlugAthletesRouteWithChildren
  AuthenticatedOrgSlugDashboardRoute: typeof AuthenticatedOrgSlugDashboardRoute
  AuthenticatedOrgSlugExercisesRoute: typeof AuthenticatedOrgSlugExercisesRoute
  AuthenticatedOrgSlugProgramsProgramIdRoute: typeof AuthenticatedOrgSlugProgramsProgramIdRoute
  AuthenticatedOrgSlugProgramsNewRoute: typeof AuthenticatedOrgSlugProgramsNewRoute
  AuthenticatedOrgSlugProgramsIndexRoute: typeof AuthenticatedOrgSlugProgramsIndexRoute
}

const AuthenticatedOrgSlugRouteChildren: AuthenticatedOrgSlugRouteChildren = {
  AuthenticatedOrgSlugAthletesRoute:
    AuthenticatedOrgSlugAthletesRouteWithChildren,
  AuthenticatedOrgSlugDashboardRoute: AuthenticatedOrgSlugDashboardRoute,
  AuthenticatedOrgSlugExercisesRoute: AuthenticatedOrgSlugExercisesRoute,
  AuthenticatedOrgSlugProgramsProgramIdRoute:
    AuthenticatedOrgSlugProgramsProgramIdRoute,
  AuthenticatedOrgSlugProgramsNewRoute: AuthenticatedOrgSlugProgramsNewRoute,
  AuthenticatedOrgSlugProgramsIndexRoute:
    AuthenticatedOrgSlugProgramsIndexRoute,
}

const AuthenticatedOrgSlugRouteWithChildren =
  AuthenticatedOrgSlugRoute._addFileChildren(AuthenticatedOrgSlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedOrgSlugRoute: typeof AuthenticatedOrgSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOrgSlugRoute: AuthenticatedOrgSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
