/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOrgSlugRouteImport } from './routes/_authenticated/$orgSlug'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedOrgSlugExercisesRouteImport } from './routes/_authenticated/$orgSlug/exercises'
import { Route as AuthenticatedOrgSlugDashboardRouteImport } from './routes/_authenticated/$orgSlug/dashboard'
import { Route as AuthenticatedOrgSlugAthletesRouteImport } from './routes/_authenticated/$orgSlug/athletes'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgSlugRoute = AuthenticatedOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedOrgSlugExercisesRoute =
  AuthenticatedOrgSlugExercisesRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugDashboardRoute =
  AuthenticatedOrgSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugAthletesRoute =
  AuthenticatedOrgSlugAthletesRouteImport.update({
    id: '/athletes',
    path: '/athletes',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/signup': typeof AuthSignupRoute
  '/$orgSlug': typeof AuthenticatedOrgSlugRouteWithChildren
  '/$orgSlug/athletes': typeof AuthenticatedOrgSlugAthletesRoute
  '/$orgSlug/dashboard': typeof AuthenticatedOrgSlugDashboardRoute
  '/$orgSlug/exercises': typeof AuthenticatedOrgSlugExercisesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/signup': typeof AuthSignupRoute
  '/$orgSlug': typeof AuthenticatedOrgSlugRouteWithChildren
  '/$orgSlug/athletes': typeof AuthenticatedOrgSlugAthletesRoute
  '/$orgSlug/dashboard': typeof AuthenticatedOrgSlugDashboardRoute
  '/$orgSlug/exercises': typeof AuthenticatedOrgSlugExercisesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authenticated/$orgSlug': typeof AuthenticatedOrgSlugRouteWithChildren
  '/_authenticated/$orgSlug/athletes': typeof AuthenticatedOrgSlugAthletesRoute
  '/_authenticated/$orgSlug/dashboard': typeof AuthenticatedOrgSlugDashboardRoute
  '/_authenticated/$orgSlug/exercises': typeof AuthenticatedOrgSlugExercisesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/$orgSlug'
    | '/$orgSlug/athletes'
    | '/$orgSlug/dashboard'
    | '/$orgSlug/exercises'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/$orgSlug'
    | '/$orgSlug/athletes'
    | '/$orgSlug/dashboard'
    | '/$orgSlug/exercises'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_auth/onboarding'
    | '/_auth/signup'
    | '/_authenticated/$orgSlug'
    | '/_authenticated/$orgSlug/athletes'
    | '/_authenticated/$orgSlug/dashboard'
    | '/_authenticated/$orgSlug/exercises'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$orgSlug': {
      id: '/_authenticated/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof AuthenticatedOrgSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/$orgSlug/exercises': {
      id: '/_authenticated/$orgSlug/exercises'
      path: '/exercises'
      fullPath: '/$orgSlug/exercises'
      preLoaderRoute: typeof AuthenticatedOrgSlugExercisesRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/dashboard': {
      id: '/_authenticated/$orgSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$orgSlug/dashboard'
      preLoaderRoute: typeof AuthenticatedOrgSlugDashboardRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/athletes': {
      id: '/_authenticated/$orgSlug/athletes'
      path: '/athletes'
      fullPath: '/$orgSlug/athletes'
      preLoaderRoute: typeof AuthenticatedOrgSlugAthletesRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedOrgSlugRouteChildren {
  AuthenticatedOrgSlugAthletesRoute: typeof AuthenticatedOrgSlugAthletesRoute
  AuthenticatedOrgSlugDashboardRoute: typeof AuthenticatedOrgSlugDashboardRoute
  AuthenticatedOrgSlugExercisesRoute: typeof AuthenticatedOrgSlugExercisesRoute
}

const AuthenticatedOrgSlugRouteChildren: AuthenticatedOrgSlugRouteChildren = {
  AuthenticatedOrgSlugAthletesRoute: AuthenticatedOrgSlugAthletesRoute,
  AuthenticatedOrgSlugDashboardRoute: AuthenticatedOrgSlugDashboardRoute,
  AuthenticatedOrgSlugExercisesRoute: AuthenticatedOrgSlugExercisesRoute,
}

const AuthenticatedOrgSlugRouteWithChildren =
  AuthenticatedOrgSlugRoute._addFileChildren(AuthenticatedOrgSlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedOrgSlugRoute: typeof AuthenticatedOrgSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOrgSlugRoute: AuthenticatedOrgSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
