import { err, ok, type Result } from 'neverthrow'

export type AthleteInvitation = {
  readonly id: string
  readonly athleteId: string
  readonly organizationId: string
  readonly createdByUserId: string
  readonly token: string
  readonly expiresAt: Date
  readonly acceptedAt: Date | null
  readonly revokedAt: Date | null
  readonly createdAt: Date
}

export type AthleteInvitationError =
  | { type: 'ALREADY_ACCEPTED'; message: string }
  | { type: 'ALREADY_REVOKED'; message: string }
  | { type: 'EXPIRED'; message: string }

type CreateAthleteInvitationInput = {
  id: string
  athleteId: string
  organizationId: string
  createdByUserId: string
  token: string
}

const INVITATION_EXPIRY_DAYS = 7

/**
 * Creates a new athlete invitation with a 7-day expiry.
 * Token must be provided as input (generated by infrastructure layer).
 */
export function createAthleteInvitation(
  input: CreateAthleteInvitationInput,
): Result<AthleteInvitation, AthleteInvitationError> {
  const now = new Date()
  const expiresAt = new Date(now.getTime() + INVITATION_EXPIRY_DAYS * 24 * 60 * 60 * 1000)

  return ok({
    id: input.id,
    athleteId: input.athleteId,
    organizationId: input.organizationId,
    createdByUserId: input.createdByUserId,
    token: input.token,
    expiresAt,
    acceptedAt: null,
    revokedAt: null,
    createdAt: now,
  })
}

/**
 * Reconstitute an AthleteInvitation from database props without validation.
 * Used when loading from the database where data is already known to be valid.
 */
export function reconstituteAthleteInvitation(props: AthleteInvitation): AthleteInvitation {
  return { ...props }
}

/**
 * Accept an invitation. Returns error if already accepted, revoked, or expired.
 */
export function acceptInvitation(
  invitation: AthleteInvitation,
): Result<AthleteInvitation, AthleteInvitationError> {
  if (invitation.acceptedAt !== null) {
    return err({ type: 'ALREADY_ACCEPTED', message: 'Invitation has already been accepted' })
  }
  if (invitation.revokedAt !== null) {
    return err({ type: 'ALREADY_REVOKED', message: 'Invitation has been revoked' })
  }
  if (invitation.expiresAt < new Date()) {
    return err({ type: 'EXPIRED', message: 'Invitation has expired' })
  }

  return ok({
    ...invitation,
    acceptedAt: new Date(),
  })
}

/**
 * Revoke an invitation. Returns error if already accepted or already revoked.
 */
export function revokeInvitation(
  invitation: AthleteInvitation,
): Result<AthleteInvitation, AthleteInvitationError> {
  if (invitation.acceptedAt !== null) {
    return err({ type: 'ALREADY_ACCEPTED', message: 'Cannot revoke an accepted invitation' })
  }
  if (invitation.revokedAt !== null) {
    return err({ type: 'ALREADY_REVOKED', message: 'Invitation is already revoked' })
  }

  return ok({
    ...invitation,
    revokedAt: new Date(),
  })
}

/**
 * Checks if the invitation has expired.
 */
export function isExpired(invitation: AthleteInvitation): boolean {
  return invitation.expiresAt < new Date()
}

/**
 * Checks if the invitation has been revoked.
 */
export function isRevoked(invitation: AthleteInvitation): boolean {
  return invitation.revokedAt !== null
}

/**
 * Checks if the invitation has been accepted.
 */
export function isAccepted(invitation: AthleteInvitation): boolean {
  return invitation.acceptedAt !== null
}

/**
 * Checks if the invitation is still valid (not expired, not revoked, not accepted).
 */
export function isValid(invitation: AthleteInvitation): boolean {
  return !isExpired(invitation) && !isRevoked(invitation) && !isAccepted(invitation)
}
